### ISSUE TITLE
Crashes on Linux Mint 20

### ISSUE THREAD

**Issue by everettmp** [the-lay/ulauncher-spotify-api#1]
I recently decided to install ulauncher on my Linux Mint device and installed this extension. Unfortunately, after installing it, I saw that it had crashed. It gave me a command to run which I ran and restarted ulauncher, but unfortunately, it still crashed. It did give me an error message, telling me to check the logs, but I couldn't find where the logs were.

**Comment by the-lay** [comment]
First of all, thanks for checking out the extension!

It sounds very much like a dependency error - as mentioned in the readme, you need to manually install Spotify API python wrapper before you can use this extension. In the future, ulauncher will support extension requirements, so later this won't be necessary, but for now, could you please run `pip3 install -e git+git://github.com/plamere/spotipy@004df7b#egg=spotipy` or `pip install -e git+git://github.com/plamere/spotipy@004df7b#egg=spotipy` in the terminal and retry again?

I will also update readme to make it a bit more clear.

**Comment by the-lay** [comment]
With latest patch I have added auto installation of dependencies. That should ease the installation. Please let me know if this problem still occurs otherwise.
