### ISSUE TITLE
The extension crashed because it could not import module spotipy. 

### ISSUE THREAD

**Issue by metealptekin** [the-lay/ulauncher-spotify-api#12]

**Comment by the-lay** [comment]
Thank you for reporting a problem!

On the first run, the extension will try to install requirements automatically. However, if it fails, you have to do it manually. Please run: `pip3 install -r requirements.txt` from extension folder (should be something like `/home/ilja/.local/share/ulauncher/extensions/com.github.the-lay.ulauncher-spotif-api`).

**Comment by the-lay** [comment]
You did not specify any details (please do, otherwise I can't help much), but it is possible that you have multiple python installations on your system. Please try running the pip install on the default Python installation: `/usr/bin/python3 -m pip install "spotipy>=2.16.1" "requests>=2.23.0"`.

**Comment by metealptekin** [comment]
thanks for the support
