### ISSUE TITLE
ModuleNotFoundError with spotipy installed. 

### ISSUE THREAD

**Issue by iSnkh** [the-lay/ulauncher-spotify-api#13]
### Steps to reproduce
1. Install module with Extensions (add extensions)
2. Install SpotiPy with pip3 install -r requirements.txt 
3. Reinstall module 

### Environment
**Ulauncher version**: Extension API v2.0.0
**Linux distro**: Xubuntu 20.04.1 LTS (Focal Fossa)
**Desktop environment**: XFCE - PyEnv (using 3.9.0 by default)

### Logs
2020-12-09 17:58:59,902 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.the-lay.ulauncher-spotify-api" exited instantly with code 1
2020-12-09 17:58:59,903 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.the-lay.ulauncher-spotify-api" failed with an error: ModuleNotFoundError: No module named 'spotipy'

**Comment by the-lay** [comment]
Thank you for reporting the issue!

1. Is it possible that you have multiple python installations on your system? It is possible that Ulauncher uses the default system python installation, while you've installed it on some venv or conda environments.
 
2. When you ran `pip3 install ...` did spotipy module install or were there any issues there? Can you try importing spotipy separately (`python3` -> `import spotipy`)?

**Comment by iSnkh** [comment]
Hi, no issues when i install spotipy with pip3 install spotipy and importing separately?

**Comment by the-lay** [comment]
You mentioned that you are using PyEnv, so you definitely have multiple python environments on your system. Make sure you are installing spotipy library for the right python, the one that ulauncher uses. Most likely it is not the one that PyEnv provides (`/home/USER/.pyenv/....`), but the default one (`/usr/bin/python3`). If that is the case, you can try running `/usr/bin/python3 -m pip install "spotipy>=2.16.1" "requests>=2.23.0"` (his is an equivalent to pip3) and then retrying the plugin.

**Comment by iSnkh** [comment]
Thank's you, its working perfectly sorry for the useless issues good day

**Comment by the-lay** [comment]
No worries! Glad it worked out :)
