### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by OmarShawky1** [the-lay/ulauncher-spotify-api#14]
when i try to search for a song; it suggests an open spotify app to play on as following:
![image](https://user-images.githubusercontent.com/51538094/104844306-42b0df00-58d8-11eb-82fb-5a2ea27ef0b7.png)
 
and when i press enter this message occurs
![image](https://user-images.githubusercontent.com/51538094/104844316-52c8be80-58d8-11eb-96ec-93426cd92eb4.png)

OS: Elementary OS Hera 5.1.7 based on Ubuntu 18.04

**Comment by the-lay** [comment]
First of all, thank you for reporting the bug!

There can be multiple problems here.  
It seems the Spotify is running and API sees it, but it was not successful at starting the playback.  
It is very tough to diagnose this bug, but my guess is that it is on the API side, not ours.  

The immediate fix would probably be to just restart the client on your laptop and try the same again.  
Please try and let me know if that helped :) 

Also, just a small note, the search keyword is `sp search QUERY`, not  `sp QUERY` - check out `sp help` or `sp ?` for more info about that.

**Comment by OmarShawky1** [comment]
Sorry for the extremly late reply.

I tried every possible solution to make it work but i failed. the same error prevailed. However, the searching `sp search <query>` gave me results as the following example.
![image](https://user-images.githubusercontent.com/51538094/105388812-c55ed480-5c1f-11eb-92a1-bc50ae172e06.png)

It does not permit me to play (it returns 403 forbidden error).

**Comment by OmarShawky1** [comment]
unfortunately, you are right.... i tried to help you and debug it and that is what i found [Issue on spotify developer community ](https://community.spotify.com/t5/Spotify-for-Developers/Spotify-api-error-403/td-p/5025323)

**Comment by the-lay** [comment]
> Sorry for the extremly late reply.

No worries!

Sorry, I've assumed you have a premium account. As mentioned in the Troubleshooting section of README, play endpoint is only for paid Spotify subscribers. Unfortunately, that's a Spotify limitation.
