### ISSUE TITLE
Can`t running on Fedora 3 [Gtk 4]

### ISSUE THREAD

**Issue by fariias** [the-lay/ulauncher-spotify-api#17]
Hi! first, congrats for this beautiful extension.

currently i`m trying to run the extension on Fedora 34 with GTK 4, but i`m getting this error:

Traceback (most recent call last):
  File "/home/juniorfarias/.local/share/ulauncher/extensions/com.github.the-lay.ulauncher-spotify-api/main.py", line 5, in <module>
    from ulauncher.api.shared.item.ExtensionResultItem import ExtensionResultItem # noqa
  File "/usr/lib/python3.9/site-packages/ulauncher/api/shared/item/ExtensionResultItem.py", line 6, in <module>
    from ulauncher.utils.image_loader import load_image
  File "/usr/lib/python3.9/site-packages/ulauncher/utils/image_loader.py", line 9, in <module>
    from gi.repository import Gtk, Gio, GLib, GdkPixbuf
  File "/usr/lib64/python3.9/site-packages/gi/importer.py", line 139, in load_module
    raise ImportError(e)
ImportError: Requiring namespace 'Gdk' version '3.0', but '4.0' is already loaded

**Comment by the-lay** [comment]
Hi @fariias , thanks and thank you for the issue!
I don't have Fedora to test it out, but I tried googling and it seems to be a ulauncher's problem: [#703](https://github.com/Ulauncher/Ulauncher/issues/703). There is a pull request to ulauncher codebase that should fix this, but for now the only workaround that is mentioned is to remove gtk4, not sure if that works for you.

**Comment by the-lay** [comment]
On a second thought, I checked out that pull request and it seems that it is possible to fix it on the extension level, by explicitly importing gnome libraries myself. I will check it out tomorrow!

**Comment by the-lay** [comment]
@fariias sorry for taking so long to fix this! I've installed Fedora 34 VM and tested it out. Should be fixed now, please retry if you can :)

**Comment by fariias** [comment]
Hi @the-lay!

I reinstalled the extension and everything worked perfectly now! 

Thank you very much! \o/ \o/ \o/

**Comment by the-lay** [comment]
Glad to hear! Thank you for reporting the issue!
