### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by marcemarin** [the-lay/ulauncher-spotify-api#19]
Hello, the extension is awsome, unfortunately i can't try it, this is the error:
Message: 'com.github.the-lay.ulauncher-spotify-api'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.the-lay.ulauncher-spotify-api'

```

**Comment by the-lay** [comment]
Hi, thank you for opening the issue! Unfortunately, this is the first time I see this error. Also, it seems that the error comes from outside of extension code. 

Could you answer few question please, that should help me with debugging:
1. Which OS do you use?
2. What is your ulauncher version? You can check it in About tab.
3. How did you install the extension? Through Add extension in the Extensions tab?
4. Did you try restarting ulauncher or reinstalling the extension?
5. If you go to `~/.local/share/ulauncher/extensions`, do you see `com.github.the-lay.ulauncher-spotify-api` folder?

Thanks!

**Comment by the-lay** [comment]
I have found someone reported a similar problem on a different ulauncher extension and it was due to missing dependencies. So I have a follow up question, did you check the [Installation](https://github.com/the-lay/ulauncher-spotify-api#installation) section?

**Comment by the-lay** [comment]
Feel free to reopen the issue if the installation doesn't help.
