### ISSUE TITLE
Add a `next` (and maybe `previous`) command.

### ISSUE THREAD

**Issue by JDPDO** [the-lay/ulauncher-spotify-api#22]
Hey again :smiley: 

## The problem
Sometimes I want to skip a song fast. The loading screen (when the app gets the current status from spotify) in this scenario adds overhead time.

## The solution
You do not have to wait for the loaded status to skip a song if you could type `sp next` (and `sp previous`) immediately.

@the-lay If it suits you I would prepare a fork. :wink:

**Comment by the-lay** [comment]
Hey hey!

Thanks for the suggestion!
No worries, I will implement it myself today, it should only be two new queries in `on_keyword_query` and updated help menu :)

**Comment by the-lay** [comment]
Try out the new 56dbd95 version and let me know what you think!
I decided to also replace most icons with the actual spotify icons, I think this looks much neater now :)
